grep 21/open/tcp//ftp/ services.gnmap | cut -d " " -f2 > services/ftp-21.txt
grep 22/open/tcp//ssh/ services.gnmap | cut -d " " -f2 > services/ssh-22.txt
grep 23/open/tcp//telnet/ services.gnmap | cut -d " " -f2 > services/telnet-23.txt
grep 25/open/tcp//smtp/ services.gnmap | cut -d " " -f2 > services/smtp-25.txt
grep 53/open/tcp//domain/ services.gnmap | cut -d " " -f2 > services/domains-53.txt
grep 80/open/tcp//http/ services.gnmap | cut -d " " -f2 > services/web-80.txt
grep 135/open/tcp//msrpc/ services.gnmap | cut -d " " -f2 > services/rpc-135.txt
grep 139/open/tcp//netbios-ssn/// services.gnmap | cut -d " " -f2 > services/netbios-139.txt
grep 389/open/tcp//ldap/ services.gnmap | cut -d " " -f2 > services/ldap-389.txt
grep 443/open/tcp//https/ services.gnmap | cut -d " " -f2 > services/web-443.txt
grep 445/open/tcp//microsoft-ds/ services.gnmap | cut -d " " -f2 > services/smb-445.txt
grep 623/open/tcp//ipmi services.gnmap | cut -d " " -f2 > services/ipmi-623.txt
grep 990/open/tcp//ftp services.gnmap | cut -d " " -f2 > services/ftp-990.txt
grep 1099/open/tcp//rmiregistry/ services.gnmap | cut -d " " -f2 > services/rmiregistry-1099.txt
grep 1433/open/tcp//ms-sql-s/ services.gnmap | cut -d " " -f2 > services/sql-server-1433.txt
grep 1521/open/tcp//oracle/ services.gnmap | cut -d " " -f2 > services/oracle-1521.txt
grep 1723/open/tcp//pptp services.gnmap | cut -d " " -f2 > services/pptp-1723.txt
grep 2049/open/tcp//nfs/ services.gnmap | cut -d " " -f2 > services/nfs-2049.txt 
grep 3306/open/tcp//mysql services.gnmap | cut -d " " -f2 > services/mysql-3306.txt
grep 5800/open/tcp//vnc services.gnmap | cut -d " " -f2 >> services/vnc-5900.txt
grep 5900/open/tcp//vnc services.gnmap | cut -d " " -f2 >> services/vnc-5900.txt
grep 5901/open/tcp//vnc services.gnmap | cut -d " " -f2 >> services/vnc-5900.txt
grep 6000/open/tcp//x11 services.gnmap | cut -d " " -f2 > services/x11-6000.txt
grep 7000/open/tcp//http services.gnmap | cut -d " " -f2 > services/tomcat-7000.txt
grep 7001/open/tcp//afs3 services.gnmap | cut -d " " -f2 > services/afs3-callback-7001.txt
grep 8080/open/tcp//http services.gnmap | cut -d " " -f2 > services/web-8080.txt
grep 8082/open/tcp/ services.gnmap | cut -d " " -f2 > services/blackice-8082.txt
grep 8000/open/tcp//http services.gnmap | cut -d " " -f2 > services/web-8000.txt
grep 8443/open/tcp//https/ services.gnmap | cut -d " " -f2 > services/web-8443.txt
grep 9100/open/tcp// services.gnmap | cut -d " " -f2 > services/jetdirect-9100.txt
grep 9200/open/tcp// services.gnmap | cut -d " " -f2 > services/wap-wsp-9200.txt
grep 27001/open services.gnmap | cut -d " " -f2 > services/cisco-27001.txt
